logging:
  level:
    org.springframework: ERROR
    microsvc: INFO

server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://mysql5:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: demo
