info:
  app:
    name: @project.name@
    description: Customer service based on Spring Boot.
    version: @project.version@

logging:
  level:
    org.springframework.web.servlet: DEBUG
    org.springframework: ERROR
    microsvc.sb: DEBUG
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: error

management:
  endpoints:
    web:
      exposure:
        include: beans, env, flyway, health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8081
  error:
    include-message: always

spring:
  main:
    banner-mode: CONSOLE
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: demo
    validation-query: SELECT 1
