logging:
  level:
    org.springframework: ERROR
    microsvc: INFO

server:
  port: 8083
  error:
    include-message: always

service:
  configs:
    - name: account
      url: http://account:8082

spring:
  datasource:
    url: jdbc:mysql://mysql5:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: demo
