logging:
  config: classpath:/logback-k8s.xml
  level:
    org.springframework.web.servlet: ERROR
    org.springframework: ERROR
    microsvc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: beans, env, flyway, health, info, prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  error:
    include-message: always

service:
  configs:
    - name: account
      url: http://account-sb

spring:
  datasource:
    url: jdbc:mysql://mysql5:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: demo
