info:
  app:
    name: account-sb
    description: Account service based on Spring Boot.
    version: @project.version@

logging:
  level:
    #root: ERROR # set root level in logback config
    org.springframework.web.servlet: DEBUG
    org.springframework: ERROR
    microsvc: DEBUG
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: error

server:
  port: 8082
  error:
    include-message: always

service:
  configs:
    - name: customer
      url: http://localhost:8081

spring:
  main:
    banner-mode: CONSOLE
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: demo
    validation-query: SELECT 1
