logging:
  level:
    org.springframework: ERROR
    microsvc: INFO

server:
  port: 8082
  error:
    include-message: always

service:
  configs:
    - name: customer
      url: http://customer:8081

spring:
  datasource:
    url: jdbc:mysql://mysql5:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: demo
